FROM python:3.9
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["sh", "-c", "python manage.py makemigrations DockerDevops && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

